name: mariposa_material
version: 0.0.0
author: Tobe O <thosakwe@gmail.com>
description: MDL widgets for Mariposa.
homepage: https://github.com/mariposa-dart/material
environment:
    sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  js: ^0.6.1
  mariposa: ^1.0.0
dev_dependencies:
  build_runner: ^0.7.0
  build_web_compilers: ^0.4.0
  mariposa_test: ^1.0.0
  test: ^0.12.15