name: mariposa_material
version: 0.0.0
author: Tobe O <thosakwe@gmail.com>
description: MDL widgets for Mariposa.
homepage: https://github.com/mariposa-dart/material
environment:
    sdk: ">=1.19.0"
dependencies:
  js: ^0.6.1
  mariposa:
      git: https://github.com/mariposa-dart/mariposa.git
dev_dependencies:
  test: ^0.12.15